### ISSUE TITLE
Adding new links should be done with PUT

### ISSUE THREAD

**Issue by KellerFuchs** [Queertoo/Queerlink#1]
Retrieving a shortened link (as a redirect or JSON-formated data) is done using `GET`, which is perfectly sane (it is indeed safe & idempotent).

However, adding new redirects is done using `POST`, which is a non-safe and non-idempotent HTTP method: while this is valid, the information that this is an idempotent operation (adding the same URL multiple times yields the same `id`) is lost.
I suggest that this should be done using the `PUT` method, while still accepting `POST` for backwards compatibility.

See https://tools.ietf.org/html/rfc7231#section-4.2 for the definition, but in a nutshell:
- _safe_ methods should not trigger content modification, and the associated content can be cached and pre-fetched;
- _idempotent_ methods should not have additional effects when used more than once; for example, this enables the client to safely retry in case of network issues.

**Comment by ghost** [comment]
> I suggest that this should be done using the PUT method

Yeah, sounds reasonable

> while still accepting POST for backwards compatibility

There is nothing behind us, nobody's going to have to change their code because of that (I use HTTPie  to use the service :p)

**Comment by KellerFuchs** [comment]
Awesome  <3
